export default function SuggestionChips({ onSelect }) {
  const suggestions = [
    { label: "🔍 Analyze SAUCE", query: "Analyze SAUCE 0.0.731861" },
    { label: "⚖️ Compare SAUCE vs KARATE", query: "Compare the risk profiles of 0.0.731861 and 0.0.2283230" },
    { label: "🛡️ Is DOVU safe?", query: "What is the rug probability for DOVU right now?" },
    { label: "🚨 Latest Alerts", query: "Show me the latest security alerts generated by the agents" }
  ]

  return (
    <div className="flex flex-wrap gap-2 mt-4 justify-center md:justify-start">
      {suggestions.map((s, i) => (
        <button
          key={i}
          onClick={() => onSelect(s.query)}
          className="px-3 py-1.5 rounded-full border border-[#333333] bg-[#111111] text-slate-300 text-xs hover:bg-white hover:text-black hover:border-white transition-all font-medium whitespace-nowrap"
        >
          {s.label}
        </button>
      ))}
    </div>
  )
}
